### ISSUE TITLE
add "intermediate" option for commands based upon which commands will be intelligently grouped for super-efficient caching

### ISSUE THREAD

**Issue by jmversteeg** [launchdeckio/katapult#12]
Example: suppose `npm install` is only necessary to subsequently run `gulp`. If both assets to be built as well as the package.json contents have not been changed and there is a cached result for `gulp`, we could simply skip  `npm install` and go straight to restoring `gulp` from cache.

```yaml
install:
  - cmd: npm install
    input: package.json
    output: node_modules
    intermediate: true

build:
  - cmd: gulp
    input:
      - assets
      - node_modules
      - gulpfile.js
```

Based on the following conditions, `npm install` could then be skipped:
 - `assets` and `gulpfile.js` are in the repository and have not changed
 - `node_modules` is not present in the repository but apparently provided by `npm install` and the `package.json` contents have not changed thus it can be presumed that the `node_modules` content will be the same as well
