### ISSUE TITLE
Allow specification of ttl for cacheable commands

### ISSUE THREAD

**Issue by jmversteeg** [launchdeckio/katapult#2]
Example:
```yaml
  - cmd: npm install
    input: package.json
    output: node_modules
    ttl: 1 day
```
Parse times using [human-interval](https://www.npmjs.com/package/human-interval)
